unbind-key C-b

set-option -g prefix C-Space

bind-key C-Space send-prefix

setw -g mode-keys vi

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z 
bind-key -Tcopy-mode-vi Y send -X copy-pipe "xclip -in -selection clipboard -r"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'Morantron/tmux-fingers'

set -g status-position top
set -g default-terminal 'screen-256color'

run '~/.tmux/plugins/tpm/tpm'
